
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_168
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_169
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_170
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_171
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_172
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_173
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_174
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_175
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_176
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_177
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_178
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_179
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_180
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_181
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_182
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_183
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_184
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_185
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_186
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_187
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_188
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_189
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_190
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_191
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_192
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_193
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_194
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_195
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_196
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_197
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_198
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_199
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_200
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_201
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_202
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_203
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_204
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_205
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_206
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_207
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_208
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_209
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_210
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_211
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_212
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_213
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_214
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_215
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_216
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_217
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_218
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_219
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_220
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_221
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_222
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_223
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_224
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_225
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_226
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_227
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_228
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_229
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_230
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_231
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_232
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_233
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_234
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_235
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_236
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_237
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_238
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_239
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_240
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_241
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_242
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_243
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_244
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_245
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_246
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_247
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_248
mkdir -p /home/adeshpan/Desktop/core/adeshpan-prod/testWorkingDirectory/wheelnavcore-output/coreOutput_249